appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
provider: {win: azure}
travis:
  secure: {BINSTAR_TOKEN: kSjpi2cN0lBAqDms2H7avasUrx0kk7gflKnVWHuSlxhP1FXLRPDLhmMc4nrp777I0TKR+524KUWUxg/eWZ0a4MFNAcTqyNBdSli1D6pJhQ1qFHjmZMyqfJK5V2BgEQXhQPzgb4CUCY6pc1C0SLimm/sLBbKoWUKGVNNi/bCCUGWfqBBHzy3Rehjg4aHw0u+4QejDbgqEyl0eLRjStStehlepgkoBrLMRDYwCHNyS7Vq5vx+TGfIFVhVCptLFKzzA0/VqKBCR5sHKnC8MlgJxs7uLByMzo2eqrIPecCTbLrAxU6ZmOTOFdpF1IlyLF/UeHItbIqDWIdsOHrcvI3VPIevxt49Jes74paDtu4lX/NV91b3hs3hxd2qUdeGetSxMipmwnGME2slA43dxwLlxGU9wQlUNExRA8kNznOhetN11JT4MEY9XDbuIFrl0wi6zkpXP9lxRXQNaU9is3kuDJORXzEJWSsQk8RSJF+Xg/yDpZ+WYLp97r7teTb1duTz/CMvJUgTVrvALJ3igpPWdyTiGt7C8lu2/22orMhATMwy9Fev35DvnbvxI9a3MJq7iJ2wEZE5Ie+WljaLt5Kv6w09G+eZf6d2MxAM5wcCmXhubCsZq4oUHTcbmq/jAxYB+kKK8PIx/H7JbbFqHg2bZtQz45zBao9f0CFERcnW8m5c=}
bot:
  automerge: true
